fix: update disclaimer copy
politics-rewired/Spoke pull request #1054
Opened 2022-01-27 20:36 UTC by bchrobot

## Description

Update campaign upload exclusion disclaimer copy.

## Motivation and Context

Dialing it in a little bit more.

## How Has This Been Tested?

N/A

## Screenshots (if appropriate):

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation Changes

N/A

## Checklist:

- [x] My code follows the code style of this project.
- [x] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2022-01-27 21:06 UTC, kohlee approved these changes

2022-01-28 02:25 UTC, ajohn25 commented on src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/SelectExcludeCampaigns.tsx
> +        campaigns (regardless of whether they have been texted yet in that
```suggestion
        campaign (regardless of whether they have been texted yet in that
```

2022-01-28 02:27 UTC, ajohn25 requested changes

2022-01-28 02:27 UTC, ajohn25 commented on src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/SelectExcludeCampaigns.tsx
> +        campaigns (regardless of whether they have been texted yet in that
```suggestion
        campaign (regardless of whether they have been texted yet in that
```
grammar fix

2022-02-02 20:16 UTC, merged