feat: use rewired/assemble brand palette
politics-rewired/Spoke pull request #1228
Opened 2022-05-20 23:46 UTC by bchrobot

## Description

Switch to Rewired brand palette.

## Motivation and Context

Coherent visual identity.

## How Has This Been Tested?

This has been tested locally.

## Screenshots (if appropriate):

TBD

## Documentation Changes

N/A

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2022-08-31 17:44 UTC, ajohn25 commented
@bchrobot only flag at a quick glance is for the campaign builder. See below for the white/grey only and with no `<Avatar>` gray circles suggestions from Asana. I think possibly same idea for the texter "send first messages" etc. buttons to also stay white but defer to @kennyycheng!
![image](https://user-images.githubusercontent.com/76596635/187744079-e8fcd2d0-2304-45a6-b3ce-b3d9f2db7f99.png)

2022-08-31 18:40 UTC, kennyycheng commented
> 

@ajohn25 Oh yeah, good call! I have a little handoff spec if that helps out here. It has the avatar circles (just a little lighter though?), but I don't have strong feelings about keeping it or removing it, so long as the icon+color still feel apparent.

![frame_195](https://user-images.githubusercontent.com/98345372/187751411-a78b5b0a-4609-43bd-883d-f13a77982d55.png)

Otherwise, I think the rest of the palette looks good to me @bchrobot!

2022-09-02 16:04 UTC, ajohn25 approved these changes
🔥

2022-09-02 16:04 UTC, ajohn25 commented on src/containers/AdminExternalSystems.tsx
> +import Fab from "@material-ui/core/Fab";
The `<Fab>` upgrades here should be across the board so could either disable the v0 imports and close #1381 or check off that first checkbox and do a quick separate PR for disabling imports!

2022-09-02 16:04 UTC, ajohn25 commented on src/containers/AdminCampaignEdit/index.jsx
> -          if (sectionIsSaving) {
gotta love all the red here 😁

2022-09-08 14:35 UTC, hiemanshu commented
Sorry for taking a bit to get into this @bchrobot and @politics-rewired/organizing. Here's the results from my contrast tests. A bunch of places we need to work on and get alternative colors. To quickly explain readable results, AA stands for Ideal Support with Normal Text size and Large Text Size (Large Text needs a lower contrast ratio to pass), AAA stands for Specialized Support, something we can choose to not worry about for a little bit. AA is the recommended minimum to pass. 

## Passed:
<img width="721" alt="Screenshot 2022-09-08 at 7 47 23 PM" src="https://user-images.githubusercontent.com/367605/189148498-b3a4bfb5-91e0-46f5-b159-dfa026b4df2f.png">
<img width="711" alt="Screenshot 2022-09-08 at 7 47 49 PM" src="https://user-images.githubusercontent.com/367605/189148507-aaa24cdc-e94b-41db-9a36-870b76ffd85f.png">
<img width="729" alt="Screenshot 2022-09-08 at 7 49 46 PM" src="https://user-images.githubusercontent.com/367605/189148513-e7c9f91d-9f10-4dee-996a-99844e44a55b.png">
<img width="725" alt="Screenshot 2022-09-08 at 7 51 35 PM" src="https://user-images.githubusercontent.com/367605/189148537-eb06f503-7079-48ef-bf7e-2ca46d3e2748.png">
<img width="740" alt="Screenshot 2022-09-08 at 7 51 52 PM" src="https://user-images.githubusercontent.com/367605/189148547-a0788abd-89ce-4e41-8d8a-c8556fa29454.png">
<img width="709" alt="Screenshot 2022-09-08 at 7 54 54 PM" src="https://user-images.githubusercontent.com/367605/189148552-195be5a4-d8ff-4773-804c-2dd146808157.png">
<img width="737" alt="Screenshot 2022-09-08 at 7 35 42 PM" src="https://user-images.githubusercontent.com/367605/189148559-296ac447-e8d0-4bb9-b609-8d9f1b6eda9a.png">
<img width="726" alt="Screenshot 2022-09-08 at 7 36 17 PM" src="https://user-images.githubusercontent.com/367605/189148567-9506d9ac-c75f-43fd-9298-bb5bb47c7083.png">
<img width="708" alt="Screenshot 2022-09-08 at 7 37 39 PM" src="https://user-images.githubusercontent.com/367605/189148584-2af67e2c-bd7c-4e33-bc04-1be4ce0af206.png">
<img width="723" alt="Screenshot 2022-09-08 at 7 41 19 PM" src="https://user-images.githubusercontent.com/367605/189148616-e81f6720-fc4c-446e-a7a2-656aad52bbf2.png">

## Failed: 
### Script Editor Custom Fields
<img width="718" alt="Screenshot 2022-09-08 at 7 44 57 PM" src="https://user-images.githubusercontent.com/367605/189148469-0525b570-18b9-46b0-a523-0481bd1bd5fc.png">

### Optout Button
<img width="718" alt="Screenshot 2022-09-08 at 7 50 15 PM" src="https://user-images.githubusercontent.com/367605/189148523-7190f54a-e473-4612-b79b-59cf2a41ae83.png">

### Campaign Name (Campaign List)
<img width="731" alt="Screenshot 2022-09-08 at 7 36 54 PM" src="https://user-images.githubusercontent.com/367605/189148573-0d72b505-3c75-4212-afd1-84de30b66259.png">

### Completed Campaign Name (Campaign List)
<img width="744" alt="Screenshot 2022-09-08 at 7 38 36 PM" src="https://user-images.githubusercontent.com/367605/189148600-cdf164d3-dd46-4ddb-9b94-ceb764af919b.png">

### Details Page Overdue Date
<img width="731" alt="Screenshot 2022-09-08 at 7 39 27 PM" src="https://user-images.githubusercontent.com/367605/189148607-68d881b4-2a06-4dff-8f65-cd33382dc273.png">

### Uncompleted Sections Campaign Editor
<img width="744" alt="Screenshot 2022-09-08 at 7 43 20 PM" src="https://user-images.githubusercontent.com/367605/189148621-8619b760-20e6-4815-ba7e-73e5c1e5bbb6.png">

2022-09-08 15:17 UTC, hiemanshu requested changes
Overall looks good! A few places has hard coded colors, those should be replaced. And we should talk about the color contrasts that are failing.

2022-09-08 17:10 UTC, hiemanshu commented
From the failed ones, the most commonly seen ones/ones that need immediate attention would be:

Script Editor Custom Fields
Campaign Name (Campaign List)
Completed Campaign Name (Campaign List)

2022-09-12 11:57 UTC, hiemanshu approved these changes

2022-09-12 12:02 UTC, merged