feat: support campaign variables in scripts
politics-rewired/Spoke pull request #1234
Opened 2022-05-23 10:45 UTC by bchrobot

## Description

This adds support for using campaign variables in scripts. As part of this, it also stores the ID of the exact version of the campaign variables used in the message.

## Motivation and Context

Closes #1184.

## How Has This Been Tested?

This has been tested locally and in limited beta releases.

## Screenshots (if appropriate):

<table><tr><td>

<img width="603" alt="Screen Shot 2022-05-23 at 6 38 35 AM" src="https://user-images.githubusercontent.com/2145526/169802630-7a42194b-3b1d-4956-81c4-a3a5b3c5e653.png">

</td></tr><tr><td>

<img width="1122" alt="Screen Shot 2022-05-23 at 6 38 47 AM" src="https://user-images.githubusercontent.com/2145526/169802678-a35923f7-ab2c-4d84-a991-fa0c7d0f87a7.png">

</td></tr></table>

## Documentation Changes

Documentation has not yet been written.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2022-05-23 19:40 UTC, ajohn25 commented
I think we do want the prefixes in! I can take over for that piece?

2022-07-03 11:20 UTC, hiemanshu commented
Adding in some more screenshots! And changing this to ready to review! 

<img width="1672" alt="Screenshot 2022-07-03 at 4 48 21 PM" src="https://user-images.githubusercontent.com/367605/177037127-103390d9-7a90-4022-aca5-cb1d25fbc94f.png">
<img width="629" alt="Screenshot 2022-07-03 at 4 48 29 PM" src="https://user-images.githubusercontent.com/367605/177037128-86d78589-e86a-4462-b9d3-96b56efefeef.png">

<img width="1662" alt="Screenshot 2022-07-03 at 4 48 14 PM" src="https://user-images.githubusercontent.com/367605/177037122-3cbb1cdb-e6dc-4636-b093-29cbc2903393.png">

2022-07-04 03:59 UTC, ajohn25 approved these changes

2022-07-04 03:59 UTC, ajohn25 commented on src/components/ScriptOptionBlock.tsx
> +          Script cannot use a campaign variable without a variable:{" "}
Nitpick: I think this is probably what was meant?
```suggestion
          Script cannot use a campaign variable without a value:{" "}
```

2022-07-13 20:15 UTC, ajohn25 reviewed
It seems like save is still disabled if a variable without a value is used - commenting on lines I think may be responsible below
![image](https://user-images.githubusercontent.com/76596635/178824860-2657b19d-7b01-4a37-bddc-de6e57ebe547.png)

2022-07-13 20:15 UTC, ajohn25 commented on src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
> +    (!isTemplate && hasInvalidFields) ||
Disabling save here (for non template campaigns)

2022-07-13 20:15 UTC, ajohn25 commented on src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
> +        </p>
And bringing up this warning

2022-07-14 15:30 UTC, ajohn25 requested changes

2022-07-14 15:30 UTC, ajohn25 commented on src/server/api/lib/campaign.ts
> +  const customFields = Object.keys(JSON.parse(campaignContact.custom_fields));
Required: Seems like this will error if the campaign has no contacts loaded (seen when trying to create a new campaign).

2022-07-19 02:22 UTC, ajohn25 approved these changes

2022-07-22 11:44 UTC, hiemanshu commented on src/api/campaign.ts
> +    invalidScriptFields: [String!]
It is actually nullable, because you can have no script fields that are invalid in a campaign.

2022-07-22 11:46 UTC, hiemanshu commented
@bchrobot changes made! Let me know if this is good to go!

2022-07-22 12:04 UTC, hiemanshu commented on src/api/campaign.ts
> +    invalidScriptFields: [String!]
It does return an empty array, I'll fix the type def!

2022-07-22 12:11 UTC, merged