feat: store and export filtered contacts
politics-rewired/Spoke pull request #1320
Opened 2022-07-13 14:55 UTC by hiemanshu

also allow user to pick what files they want to export

## Description

Store filtered contacts in a DB that is `campaign_contact` + a couple of fields

## Motivation and Context

Closes #1019 

## How Has This Been Tested?

Tested locally in different configurations

## Screenshots (if appropriate):
<img width="316" alt="Screenshot 2022-07-13 at 8 24 35 PM" src="https://user-images.githubusercontent.com/367605/178764777-ed5cda49-88eb-439c-8ed9-8ad126ec54eb.png">

<img width="1271" alt="Screenshot 2022-07-13 at 8 20 16 PM" src="https://user-images.githubusercontent.com/367605/178764755-7c04653d-3b7a-4018-8276-018270e2386d.png">

## Documentation Changes

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2022-07-15 01:51 UTC, ajohn25 requested changes

2022-07-15 01:51 UTC, ajohn25 commented on src/server/lib/templates/export.tsx
> +      -- The {organizationName} Team
We actually feel like this should be hardcoded! Admins/Owners may be confused that they seem to be getting a Spoke email from their own organization. Sorry to make you undo the work to fetch this one 😢 
```suggestion
      -- The Spoke Rewired Team
```

2022-07-20 13:16 UTC, hiemanshu commented on migrations/20220708150050_add_filtered_contacts_table.js
> +    .createTable("filtered_contact", (table) => {
Nope, they aren't used for anything. They're just staying in sync with `campaign_contact`

2022-07-20 13:22 UTC, hiemanshu commented on migrations/20220708150050_add_filtered_contacts_table.js
> +    );
`checkIn` is a new function and not available yet :(

2022-07-21 17:46 UTC, ajohn25 commented on migrations/20220708150050_add_filtered_contacts_table.js
> +    .createTable("filtered_contact", (table) => {
Organizing talked about this and it should be fine to remove the columns from our perspective. In the export, we can hardcode the values as null.

2022-07-26 04:21 UTC, ajohn25 approved these changes

2022-08-08 17:31 UTC, merged