feat(bulk editor): confirm changes before updating
politics-rewired/Spoke pull request #1329
Opened 2022-07-27 15:01 UTC by hiemanshu

## Description

Confirm changes that are going to be made before making them, also fix campaign selection, and use a
select to select campaigns to edit

## Motivation and Context

Fixes #841 

## How Has This Been Tested?

Tested locally

## Screenshots (if appropriate):

<img width="1715" alt="Screenshot 2022-07-27 at 6 20 25 PM" src="https://user-images.githubusercontent.com/367605/181280817-b655f0b1-8b2e-4e04-b378-9e90eea53705.png">
<img width="1709" alt="Screenshot 2022-07-27 at 6 20 51 PM" src="https://user-images.githubusercontent.com/367605/181280823-97b1f0ee-1304-43e9-b1a0-63dcaf30dbfe.png">

<img width="1930" alt="Screenshot 2022-07-26 at 1 54 33 PM" src="https://user-images.githubusercontent.com/367605/181280779-551acdeb-10ca-4bdb-9985-eb5f126c7e30.png">

## Documentation Changes

Will requires changes on how to use the updated bulk editor

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2022-07-27 15:59 UTC, hiemanshu commented
@politics-rewired/organizing obligatory tag for you to look at screenshots!

2022-07-29 01:06 UTC, ajohn25 requested changes
So much better already 🔥 Some additional organizing feedback for ease of use:

2022-08-02 15:43 UTC, hiemanshu commented
@politics-rewired/organizing updated screenshots:

<img width="1696" alt="Screenshot 2022-08-02 at 9 11 15 PM" src="https://user-images.githubusercontent.com/367605/182416090-c0ecf810-bf9b-4256-bdb4-a03b181d4bb1.png">
<img width="1690" alt="Screenshot 2022-08-02 at 9 11 22 PM" src="https://user-images.githubusercontent.com/367605/182416098-1c8f5f60-d5fd-4201-89e3-6197a96d91f8.png">
<img width="1936" alt="Screenshot 2022-08-02 at 9 11 33 PM" src="https://user-images.githubusercontent.com/367605/182416103-bea5b395-ac41-4b68-84ec-9885c024494d.png">
<img width="1692" alt="Screenshot 2022-08-02 at 9 10 51 PM" src="https://user-images.githubusercontent.com/367605/182416066-d3209a0b-3ac3-432c-a05c-b65bd73b2ca7.png">

2022-08-02 17:05 UTC, ninabaldwin commented
@hiemanshu Everything looks amazing! Is there regex search capability in the search bar? Just wondering.

2022-08-03 02:03 UTC, ajohn25 approved these changes

2022-08-03 05:25 UTC, hiemanshu commented
> @hiemanshu Everything looks amazing! Is there regex search capability in the search bar? Just wondering.

It's a simple text filter to let you find the campaigns using their ID or name

2022-08-03 17:12 UTC, ninabaldwin commented
@hiemanshu Can we create a separate issue for the search to be regex? We don't have to do it right now but it would be nice!

2022-08-04 06:32 UTC, hiemanshu commented
@ninabaldwin done, I've created #1338

2022-08-05 07:00 UTC, hiemanshu commented on src/containers/AdminBulkScriptEditor/ChangesDialog.tsx
> +  const changes = Object.values(changesList);
Changes are a list of changes per campaign id, so we can show the changes that will happen for each script in different parts of the campaigns. See campaign 13 in the screenshot above. So the `changesList` is an object with key as campaign ID, and value as an array of Changes, I've updated the type definition and even the code a little bit to handle it better.

2022-08-08 17:38 UTC, merged