feat: allow uploading arbitrary csvs
politics-rewired/Spoke pull request #1540
Opened 2022-11-30 08:20 UTC by hiemanshu

## Description

Allow uploading arbitrary CSVs and allowing column remapping 

## Motivation and Context

Fixes #1156 

## How Has This Been Tested?

Tested locally with different variants of CSVs

## Screenshots (if appropriate):

<img width="1456" alt="Screenshot 2022-11-30 at 1 47 15 PM" src="https://user-images.githubusercontent.com/367605/204743651-84f67758-3689-4874-bcab-5a564d690977.png">
<img width="503" alt="Screenshot 2022-11-30 at 1 47 28 PM" src="https://user-images.githubusercontent.com/367605/204743669-7cdfae10-89d4-44b6-8910-95bc70a16e65.png">
<img width="501" alt="Screenshot 2022-11-30 at 1 47 55 PM" src="https://user-images.githubusercontent.com/367605/204743678-65cc1036-140b-4964-8850-d8d1b5ba38f1.png">
<img width="1456" alt="Screenshot 2022-11-30 at 1 48 16 PM" src="https://user-images.githubusercontent.com/367605/204743688-b4416513-ff9a-4a0d-8c60-48039c0d0c44.png">

## Documentation Changes

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2022-11-30 08:20 UTC, hiemanshu commented
@politics-rewired/organizing copy needed as always for the popup dialog.

2022-12-01 18:34 UTC, ninabaldwin commented
@hiemanshu We have some ideas to change it so that it is required to map every time someone loads a CSV. I have uploaded a video on how actionnetwork does it and we pretty much want to have it do the same thing:

https://user-images.githubusercontent.com/98056070/205129515-dcbf208e-7db9-47cb-be56-576dee6c6e12.mp4

On top of that, we also want it to automatically map first name, last name, etc, any field that we already map. For example, if the CSV has the headers firstName, lastName and cell then when the mapping pops up it automatically fills those in as First Name, Last Name, and Cell Phone Number. We want that for any header we accept today (i.e. firstname, firstName etc, I don't know everything we accept today) and nothing else. Everything else would be loaded with the name provided (defaults as "Load as variable"). 

So we would only "map" the special fields we use and everything else would be loaded as they have named in the file. I would recommend using normal names from everything moving forward when selecting the "mapped" field from the drop-down (not camel case) >

First Name
Last Name
Cell Phone Number
Zip
External ID
(I think these are only special fields that require mapping? not 100% sure)

And maybe everything else would default to "Load as variable"

An example:
Load a CSV with headers: lastname, phone, address, zip code, firstName

Mapping would default to:

lastname > Last Name
phone > Load as variable
address > Load as variable
zip code > Load as variable
firstName > First Name

They would need to update phone and zip code to "Cell Phone Number" and "Zip" from a drop down that only contains the last special fields that can be mapped.


Ok clearly this is a lot of info but let me know if there is anything else I can answer!

2022-12-03 19:08 UTC, ajohn25 requested changes

2022-12-03 22:33 UTC, ajohn25 commented on migrations/20221125080945_add_column_mapping_to_campaign.js
> +          messaging_service_sid
Required: Same as above
```suggestion
          messaging_service_sid,
          autosend_limit
```

2022-12-06 12:09 UTC, hiemanshu commented
> So we would only "map" the special fields we use and everything else would be loaded as they have named in the file. I would recommend using normal names from everything moving forward when selecting the "mapped" field from the drop-down (not camel case) 

So we won't allow custom column remappings of any kind? The sense I got from conversations was that we wanted to allow that to happen.

> On top of that, we also want it to automatically map first name, last name, etc, any field that we already map. For example, if the CSV has the headers firstName, lastName and cell then when the mapping pops up it automatically fills those in as First Name, Last Name, and Cell Phone Number.

It already does this. We can make a more exhaustive list if we need, here's what it currently is: https://github.com/politics-rewired/Spoke/blob/563dc7a64b3f0e1088965de3ab41abdf12ee0e85/src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx#L17-L28

It takes those names, and will automatically pop in values.

2022-12-06 18:07 UTC, ajohn25 commented
@hiemanshu you can ignore the section about changing what gets mapped since we're already doing it. We should change the dialog to pop up every time someone loads a CSV, so that it's required to do the mapping when you upload.

2022-12-07 09:35 UTC, hiemanshu commented
> @hiemanshu you can ignore the section about changing what gets mapped since we're already doing it. We should change the dialog to pop up every time someone loads a CSV (instead of having to click the Configure button). We'd like it to be required for the user to correct/confirm the mapping when you upload, and that should be the only change required from the first organizing comment!

So currently the user is required to correct/confirm the mapping when they upload. You can't save the contacts without a correct mapping. I'll make the dialog open on loading the CSV, looks like the only change since other changes already exist.

@politics-rewired/organizing do you think it would be helpful to have staging run this feature branch so that y'all can test the current behavior and see how that works?

2022-12-07 16:10 UTC, ninabaldwin commented
@hiemanshu yes that would be great!

2022-12-07 19:00 UTC, ajohn25 approved these changes

2023-01-02 14:20 UTC, hiemanshu commented
@politics-rewired/organizing https://stagingenv.spokerewired.com has this feature available now!

2023-01-03 19:52 UTC, ninabaldwin commented
@hiemanshu we want some changes!

- Change to a drop-down menu (with options "First Name," "Last Name," "Cell Phone," "External ID," "Zip" and "Create New Field")
- Do not use wording "remap to" and instead just say "Create field with name as is"
- Create new field allows them to change the name of the header to whatever they want (include an error that doesn't allow duplicates- for example it won't allow First Name

2023-01-09 20:52 UTC, ajohn25 commented
A few more changes we would like (hopefully last round 😭 :
- In addition to the duplicate error, the drop downs should have a field removed from the list if it's already been used. Ex. if the first row has "First Name" selected, no other row has "First Name" in the drop down until it's deselected in the first row.
- For columns that are not in the drop down, the autocomplete box should have a gray placeholder with "Create as" + the name of the column in the csv. Ex. an ask column by default says `Create as "ask"`
- We'd like to add a "Type new column name" option in the drop down. This is just to let users know they're able to type in their own name, since that may not be obvious at a glance. When you click that option, we just hide the drop down and let the user type.

2023-01-23 12:40 UTC, hiemanshu commented
@politics-rewired/organizing changes are up on staging for 1 and 2. Last change needed to finish up this PR is having copy for the document on how to use this, and what is required, etc. Let me know when you have the copy ready, and I'll push it to staging, so you can have the document prepared too.

2023-01-24 23:16 UTC, ninabaldwin commented
@hiemanshu you are saying we need to update this article: https://docs.spokerewired.com/article/64-contact-lists and any other articles that mention how to upload a csv?

2023-01-25 13:33 UTC, hiemanshu commented
> @hiemanshu you are saying we need to update this article: https://docs.spokerewired.com/article/64-contact-lists and any other articles that mention how to upload a csv?

Yeah. And also some copy for the dialog, talking about the required fields, and additional fields, and that you can type in custom fields too. Feel free to add in / remove any information that would make more sense going into the document.

2023-07-12 17:08 UTC, merged