feat: host-based GraphQL context
politics-rewired/Spoke pull request #560
Opened 2020-02-13 14:01 UTC by bchrobot

2020-12-02 16:16 UTC, henryk1229 approved these changes

2020-12-09 18:25 UTC, ben-pr-p requested changes
This is incredibly close to full schema tenancy and looks great overall!

2020-12-09 18:25 UTC, ben-pr-p commented on src/server/contexts.ts
> +  master: Knex;
```suggestion
  primary: Knex;
```
The world seems to be going towards this, we should follow?

2020-12-10 15:22 UTC, ben-pr-p commented
Definitely maybe later!

2020-12-10 16:39 UTC, ben-pr-p approved these changes

2020-12-10 16:39 UTC, ben-pr-p commented
I think we should do a release after merging this, before merging too much else

2020-12-11 12:54 UTC, merged