feat(users): add superadmin option to role selection
politics-rewired/Spoke pull request #850
Opened 2021-01-07 16:48 UTC by henryk1229

## Description

Closes #814, part of Q4 feature freeze.

## Motivation and Context

This allows superAdmins to manage other superAdmins by selecting the role within the People page. It's limited to superAdmins or higher within the role hierarchy, and selecting 'superadmin' prompts a confirmation dialog before running the mutation to change the role.

It also gives superadmins the option of inviting new users to join an org as superadmins explicitly

## How Has This Been Tested?

This has been tested locally.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation Changes

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

2021-01-11 21:22 UTC, ben-pr-p commented
- [ ] Set `user` `is_superadmin = true` on set to superadmin
- [ ] Return super admin in org membership resolver
- [ ] Remove migration

2021-01-14 14:26 UTC, ben-pr-p requested changes
We need to make sure that only `SUPERADMIN`'s can modify someone else's `SUPERADMIN` status on the server as well. 

Modifying https://github.com/politics-rewired/Spoke/pull/850/files#diff-6167f7d4b5d9664e676a5d148c2a2c316b56085d6ac43620eaab1aeb07e02e96R982 is probably the best place to do it

2021-01-14 15:13 UTC, ben-pr-p commented
> There shouldn't be changes to `yarn.lock` (unless those changes weren't committed alongside their associated `package.json` changes).
> 
> Try doing:
> 
> ```shell
> # Checkout just yarn.lock from the master branch
> git checkout master -- yarn.lock
> 
> yarn install
> 
> git diff
> ```

I'm also getting changes to `yarn.lock` when installing locally, so somewhere along the line someone forgot to include those. If we don't want those to be included in this PR, @bchrobot would you mind committing those to master and rebasing this?

2021-01-14 22:44 UTC, henryk1229 commented
I've got the changes from the review, but for some reason the UI still isn't reflecting the change after the editOrganizationMembership mutation runs if you assign or un-assign a user as a Superadmin, or change a user's Auto Approve level - thoughts?

2021-01-19 14:21 UTC, merged